CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(50) NOT NULL,
	description varchar(200) NOT NULL,
	release_date date NOT NULL,
	duration INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name varchar(50) NOT NULL);

CREATE TABLE IF NOT EXISTS films_mpa (
    film_id INTEGER REFERENCES films (id),
    mpa_id INTEGER REFERENCES mpa (id));

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name varchar(50) NOT NULL);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films (id),
    genre_id INTEGER REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id));

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50) NOT NULL,
    name varchar(50) NOT NULL,
    email varchar NOT NULL,
    birthday date NOT NULL);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id),
    PRIMARY KEY (film_id, user_id));

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id));